-- Fix: Profit calculation must exclude tax and include cart-level discounts
-- Previously: lineProfit included tax; cart-level discounts were ignored in profit calc
-- NOTE: fn_update_sale_totals_internal() is now maintained in 02_triggers.sql
--       (Single Source of Truth). This file is kept for historical reference only.
-- No function definitions here — all trigger logic lives in 02_triggers.sql.
