-- Fix: Remove invalid 'COMPLETED' enum value from purchase_order_status comparison
-- The purchase_order_status enum only has: DRAFT, SENT, PARTIAL, RECEIVED, CANCELLED
-- NOTE: fn_update_supplier_balance_internal() is now maintained in 02_triggers.sql
--       (Single Source of Truth). This file is kept for historical reference only.
-- No function definitions here — all trigger logic lives in 02_triggers.sql.
